export const CelebrityObj = [
  {
    name: "chuck-norris",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.78,
    birthday: "1940-03-10",
    age: 82,
    is_alive: true,
  },
  {
    name: "tom-hanks",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.83,
    birthday: "1956-07-09",
    age: 65,
    is_alive: true,
  },
  {
    name: "cate-blanchett",
    nationality: "Australia",
    occupation: "actress",
    height: 1.74,
    birthday: "1969-05-14",
    age: 52,
    is_alive: true,
  },
  {
    name: "johnny-depp",
    nationality: "Australia",
    occupation: "actor",
    height: 1.78,
    birthday: "1963-06-09",
    age: 58,
    is_alive: true,
  },
  {
    name: "kate-winslet",
    nationality: "Great Britain",
    occupation: "actress",
    height: 1.69,
    birthday: "1975-10-05",
    age: 46,
    is_alive: true,
  },
  {
    name: "leonardo-dicaprio",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.83,
    birthday: "1974-11-11",
    age: 47,
    is_alive: true,
  },
  {
    name: "elijah-wood",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.68,
    birthday: "1981-01-28",
    age: 41,
    is_alive: true,
  },
  {
    name: "ian-mckellen",
    nationality: "Great Britain",
    occupation: "actor",
    height: 1.8,
    birthday: "1939-05-25",
    age: 82,
    is_alive: true,
  },
  {
    name: "patrick-stewart",
    nationality: "Great Britain",
    occupation: "actor",
    height: 1.78,
    birthday: "1940-07-13",
    age: 81,
    is_alive: true,
  },
  {
    name: "harrison-ford",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.85,
    birthday: "1942-07-13",
    age: 79,
    is_alive: true,
  },
  {
    name: "natalie-portman",
    nationality: "Israel",
    occupation: "actress",
    height: 1.6,
    birthday: "1981-06-09",
    age: 40,
    is_alive: true,
  },
  {
    name: "morgan-freeman",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.88,
    birthday: "1937-06-01",
    age: 84,
    is_alive: true,
  },
  {
    name: "whoopi-goldberg",
    nationality: "U.S.A",
    occupation: "actress",
    height: 1.65,
    birthday: "1955-11-13",
    age: 66,
    is_alive: true,
  },
  {
    name: "anthony-hopkins",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.74,
    birthday: "1937-12-31",
    age: 84,
    is_alive: true,
  },
  {
    name: "jim-carrey",
    nationality: "Canada",
    occupation: "actor",
    height: 1.87,
    birthday: "1962-01-17",
    age: 60,
    is_alive: true,
  },
  {
    name: "frances-mcdormand",
    nationality: "U.S.A",
    occupation: "actress",
    height: 1.65,
    birthday: "1957-06-23",
    age: 64,
    is_alive: true,
  },
  {
    name: "mel-gibson",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.77,
    birthday: "1956-01-03",
    age: 66,
    is_alive: true,
  },
  {
    name: "tom-cruise",
    nationality: "U.S.A",
    occupation: "actor",
    height: 1.7,
    birthday: "1956-01-03",
    age: 59,
    is_alive: true,
  },
];
